on:
  push:
    branches: [ develop, bugfix/*, feature/*, release/*, hotfix/* ]
  pull_request:
    branches: [ develop ]

jobs:
  build-validation:
    uses: abbgrade/PsBuildTasks/.github/workflows/build-validation-matrix.yml@1.9.0
